<?php

namespace Kitpages\CompanyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function queryByGroup($groupName) {

            return $this->_em->createQueryBuilder()
                ->select('u')
                ->from('AppUserBundle:User', 'u')
                ->join('u.group', 'g')
                ->where('g.name = :name')
                ->orderBy('u.username', 'ASC')
                ->setParameter("name", $groupName);
    }


    public function getCountByEmployeeFree() {
        $query = $this->_em
            ->createQuery("
                SELECT count(u)
                FROM AppUserBundle:User u
                JOIN u.group g
                LEFT JOIN u.missionEmployeeList m
                WHERE g.name = 'employee'
                AND m.id IS NULL
            ");
        return $query->getSingleScalarResult();
    }

}